[workspace]
authors = ["Lena-Kemmelmeier <lkemmelmeier@ucsd.edu>"]
channels = ["conda-forge"]
name = "henderson2025"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
render = 'quarto render "writeup/Replication Report Template.qmd" --to html'
preview = 'quarto preview "writeup/Replication Report Template.qmd" --to html'

[dependencies]
quarto = ">=1.8.25,<2"
r-base = ">=4.5.1,<4.6"
r-knitr = ">=1.50,<2"
r-rmarkdown = ">=2.30,<3"
r-tidyverse = ">=2.0.0,<3"
